README.md, config/config.ini, src/cerberus.py
Solves: #5 
Kube scheduler is now being monitored.
=> Monitor kube scheduler

config/config.ini, src/cerberus.py
=> Provide user ability to pass custom kubeconfig file path

.travis.yml
This PR solves #8 
I have enabled travis ci to run the linters on every PR.
Please have a look @chaitanyaenr
=> Added travis ci

cerberus/invoke/command.py, cerberus/kubernetes/client.py, cerberus/server/server.py, setup.cfg, start_cerberus.py
This commit also adds support to invoke a command which is useful
in cases where there's no function available in kubernetes client
to use.
=> Split it to packages for better maintenance and resusability

README.md, containers/Dockerfile, containers/README.md
This commit also updated the container entrypoint with the new
location of the run script.
=> Add info about the quay image builds

README.md, cerberus/slack/slack_client.py, config/config.yaml, requirements.txt, start_cerberus.py
This PR solves issue: #3 
This commit:
- Adds support to send a message to a specified slack channel.
- Sends in a message when cerberus starts monitoring.
- Reports the component failures in differnt clusters and
sends the report for the same.
=> Added support for slack integration

cerberus/inspect/inspect.py, cerberus/slack/slack_client.py, start_cerberus.py
This commit:
- Updates slack notification to report the node failures
- Refactors the code to improve the code readability
=> Updated slack notification and performed code refactoring

cerberus/kubernetes/client.py
=> Fixes node_kerneldeadlock_status updation

start_cerberus.py
=> Fixes NoneType error in watch_url_routes

run_test.sh, test.sh, tests/common.sh, tests/test-configs/hello_openshift_pod.yaml, tests/test_daemon_disabled.sh, tests/test_detailed_data_inspection.sh, tests/test_list, tests/test_slack_integration.sh
Fixes #25 
This commit:
- Ensures functionality of cerberus is not affected/broken by a
new commit.
- Adds a functional test to ensure non-daemon mode of cerberus is
not affected by a new commit.
- Adds a functional test to ensure the functionality of cerberus
to collect detailed logs, events and metrics of failed components
is not affected.
- Adds a functional test to ensure the slack integration feature is
not affected by a new commit.
=> Added support to ensure functionality isn't affected on new commit

cerberus/kubernetes/client.py
This commit:
- Uses a single API call to get the status of all the pods in a
namespace at once instead of looping through the list of pods
in a namespace and making an API call to get the status of each
pod while watching_namespaces and monitoring pod crash/restart
during sleep.
- Similarly, uses a single API call to get the status of all the
nodes at once while watching_nodes.
- Similarly, uses a single API call to get the status of all the
master nodes at once while checking master taint.
- Time taken for the completion of an iteration reduced by 25%
on a 50 node cluster.
Helps in resolving cerberus scalability issue #67
=> Added support to reduce the number of API calls per iteration

start_cerberus.py
This will help us replace openshift-sdn ns with opesnhfit-ovn ns if it is an OVN cluster and then check for valid namespaces
@chaitanyaenr @yashashreesuresh
=> check for valid ns after checking for correct sdn ns

cerberus/prometheus/client.py, start_cerberus.py
This commit refactors the code to improve readability.
=> Refactored to improve readability

start_cerberus.py
This commit prevents cerberus monitoring from getting terminated
by handling the exceptions. This ensures cerberus is able to handle
scenarios like losing cluster connection, cluster shut down,
etcd leader change, rpc error, etc. Cerberus monitoring is enabled
until the user terminates, thereby enhancing the tool's reliability.
=> Prevent cerberus from terminating by handling all exceptions

README.md
Cerberus as a Python package to ease installation.
Fixes: #63
=> Cerberus as a Python package

README.md
Please have a look @chaitanyaenr
=> Updating readme with blog post link

README.md, containers/README.md, docs/alerts.md, docs/example_report.md, docs/install.md, docs/node-problem-detector.md, docs/slack.md, docs/usage.md
This commit:
- Converts the various sections in the readme into individual documents.
- Adds information on projects consuming Cerberus - Benchmark Operator and
Kraken.
- Adds community info and contributing guidelines.
=> Modify documentation to improve readability

cerberus/slack/slack_client.py, config/config.yaml, config/kubernetes_config.yaml, docs/slack.md, docs/usage.md, start_cerberus.py
Trying this again - change should be against master this time.   Update vocab to change cop to watcher.
=> Update vocabulary to use watcher instead of cop

README.md, docs/contribute.md
Adding contribute doc (same as kraken one) to cerberus repo
=> Adding contribute doc and reference in readme

start_cerberus.py
Fixes https://github.com/cloud-bulldozer/cerberus/issues/123
=> Initialize custom checks variables

cerberus/kubernetes/client.py, config/config.yaml, config/kubernetes_config.yaml, docs/usage.md, start_cerberus.py
Made the checking for schedulable master nodes optional.
#122
=> added option to look for schedulable master nodes

cerberus/kubernetes/client.py
Adding a try /except around is_url_available to be able to catch when a url is unavailable and report it properly
=> Putting try around get url for unreachables routes

README.md, docs/config.md
Some of the documentation of features has been lost. Adding them back to a specific config doc to better explain each of the components and different usages
=> Creating a more detailed doc to explain the config file

start_cerberus.py
Adding in the amount of iterations the apiserver is down to the database counter and resetting when it comes back
=> Adding api counter to db insert

requirements.txt
Was running into issues running cerberus from RHEL box without this bump
Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>
=> BumpPyYAML

cerberus/kubernetes/client.py
Adding in if statements if the invoke command returns blank/had an error when getting the pods in a certain namespace
=> Adding if statements when not able to get pods in a namespace

.pre-commit-config.yaml, cerberus/invoke/command.py, cerberus/kubernetes/client.py, start_cerberus.py
Even though we had worked on a different PR for fixing all kubectl and oc commands to use the KUBECONFIG set from the cerberus config. When running in jenkins, that workaround did not work properly I would still get errors like the below. I edited the way to get pods and get nodes to use the kubernetes python client instead. The couple of commands I could not find in the kuberenetes client I added the "--kubeconfig" option to the oc/kubectl calls. 
Also in running in jenkins I noticed we never exit with a status based on the true/false that's published. So I added in a get of the status at the very end of the iterations 
```
03-15 13:55:42.838  2022-03-15 17:55:42,636 [ERROR] Failed to run kubectl get pods --chunk-size 250 -n openshift-ingress-canary -o json
03-15 13:55:42.838  2022-03-15 …
```
=> Adding in sys exit of status and using kuberenetes client for requests

.github/workflows/docker-image.yml, containers/README.md, containers/cerberus.yml, docs/installation.md
Adding new quay image for cerberus
helps with https://github.com/cloud-bulldozer/krkn-hub/actions/runs/2220938317
=> Adding updates to quay image

config/kubernetes_config.yaml, start_cerberus.py
Need to add in check if databases is missing in config file. Added to kuberenetes based config file 
https://github.com/chaos-kubox/cerberus/issues/158
=> Adding checks if missing database section

cerberus/kubernetes/client.py, start_cerberus.py
Reused the code from https://github.com/chaos-kubox/krkn/pull/256.
Co-authored-by Sanja Bonic (sanjacodes)
=> Replace calls with Kubernetes python client

cerberus/kubernetes/client.py
Start of fixing uses of limits and using continue to get list of all namespaces and nodes using a common helper function
Need to continue with other client functions that use limit 
https://github.com/chaos-kubox/cerberus/issues/165
=> Looping through continue

cerberus/kubernetes/client.py
Needing to add loading of proxy settings if they exist on the system when using private clusters with cerberus 
with this updated code: 
```
09-27 13:48:45.716  + python start_cerberus.py --config cerberus.yaml
09-27 13:48:48.473  2022-09-27 17:48:48,141 [INFO] Starting ceberus
09-27 13:48:48.473  2022-09-27 17:48:48,152 [INFO] Initializing client to talk to the Kubernetes cluster
09-27 13:48:48.473  2022-09-27 17:48:48,216 [INFO] client set
09-27 13:48:49.034  2022-09-27 17:48:48,749 [INFO] Fetching cluster info
09-27 13:48:49.034  2022-09-27 17:48:48,931 [INFO] Cluster version is 4.12.0-0.nightly-2022-09-26-111919
09-27 13:48:49.034  2022-09-27 17:48:48,931 [INFO] Server URL: https://api.***.qe.gcp.devcluster.openshift.com:6443/
09-27 13:48:49.034  2022-09-27 17:48:48,931 [INFO] …
```
=> Adding proxy setting for private clusters in cerberus

.github/workflows/ci.yml, config/kubernetes_config.yaml, kind-config.yml, requirements.txt, start_cerberus.py
Execute CI tests and collect coverage data
=> Execute CI tests and collect coverage data

CI/master_test.sh, MANIFEST.in, containers/Dockerfile, containers/Dockerfile-ppc64le, setup.cfg
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
=> Release 1.0.1

.github/workflows/docker-image.yml, containers/README.md, containers/build_own_image-README.md, containers/cerberus.yml
=> Quay images

requirements.txt
Missing requirement
https://github.com/redhat-chaos/cerberus/issues/194
=> Req missing

containers/Dockerfile, containers/Dockerfile-ppc64le
Need to get the output option in the newer release
=> Minor release

start_cerberus.py
Terminate main process and all subprocess with killing main process 
Using `kill <pid>`
```
2023-07-25 15:49:56,772 [INFO] []
2023-07-25 15:49:56,772 [INFO] Sleeping for the specified duration: 6
2023-07-25 15:50:00,741 [INFO] Terminating cerberus monitoring by user
2023-07-25 15:50:00,746 [INFO] Final status information written to final_cerberus_info.json
```
=> End loop on kill main process 

.github/workflows/docker-image.yml, containers/Dockerfile, containers/Dockerfile-ppc64le
Need to update the reference to krkn-chaos org, this needs to go in to make sure perfscale jobs arent broken
=> Adding krkn-chaos org
