krkn-chaos/cerberus

README.md, containers/Dockerfile, containers/README.md
This commit adds support to run the tool as a container on the host
with access to kubeconfig for better portability. The plan is to add
a webhook to trigger image builds on every commit to this repo at
quay.io to make sure it has the latest code instead of the user
taking care of building the image manually.
=> Containerize cerberus

README.md, src/cerberus.py
This commit:
- Modifies the http server to listen on 0.0.0.0 to be able to query
for the go/no-go signal using the public hostname/ip of the host
on which the tool is running.
- Adds chaos testing for OpenShift as a use case.
=> Run http server on 0.0.0.0 instead of localhost

cerberus/kubernetes/client.py, config/config.yaml, start_cerberus.py
This PR solves: #17  
This PR is a continuation of #18
A single function named monitor_component() can be used to
monitor any namespace thereby preventing code redundancy.
=> Monitor any given namespace

README.md, config/config.yaml, start_cerberus.py
This PR solves: #21 
The commit enables the Cerberus tool to collect logs, metrics
and events relevant to the components when there's a failure.
Eventually, the collected data can be exposed by the http
server along with the go/no-go signal.
=> Collects logs, events and metrics of failed components

README.md, containers/Dockerfile
This commit:
- Modifies the Dockerfile to change the config file type from
ini to yaml.
- Updates README.md file to create a container using the image
quay.io/openshift-scale/cerberus:latest instead of cerberus:latest.
This prevents the podman/docker from creating a container using
cerberus:latest image that might be present on the machine it's
running. The images quay.io/openshift-scale/cerberus:latest and
cerberus:latest could be different.
=> Updated Dockerfile and README.md

tox.ini
with indentation and the names of namespace being long, 79 chars more often than not is insufficient.
Note: PyCharm has a default of 120 chars
=> Increase max line length in flake config to 100

README.md, cerberus/slack/slack_client.py, config/config.yaml, start_cerberus.py
This PR solves issue: #32 
This commit enables cop id's to be assigned for each day in config
file. The cop for the day is tagged while reporting cluster component
failures. If a cop isn't assigned or if the assinged cop isn't a
member of the slack channel or if a wrong slack member id is
provided, everyone on the channel is notified by using @here tag.
=> Added support for cerberus cop

README.md, cerberus/kubernetes/client.py, config/config.yaml, start_cerberus.py
@chaitanyaenr 
when [node problem detector](https://github.com/kubernetes/node-problem-detector) daemon is present in `openshift-node-problem-detector` namespace.  It will be able to monitor additional node conditions like KernelDeadlock and ReadonlyFilesystem
when openshift-node-problem-detector detects a problem with the node
```
2020-04-06 16:51:22,165 [INFO] Iteration 37: Node status: False
2020-04-06 16:51:22,196 [INFO] Iteration 37: openshift-etcd: True
2020-04-06 16:51:22,224 [INFO] Iteration 37: openshift-apiserver: True
2020-04-06 16:51:22,504 [INFO] Iteration 37: openshift-kube-apiserver: True
2020-04-06 16:51:22,722 [INFO] Iteration 37: openshift-monitoring: False
2020-04-06 16:51:22,727 [INFO] Iteration 37: openshift-kube-controller: True
2020-04-06 16:51:22,754 [INFO] …
```
=> add node problem detector

README.md, config/config.yaml, start_cerberus.py
When the cop slack id's are not defined, the slack_team_alias tag
is used while reporting failures in the slack channel if the
slack_team_alias tag is set in the config.
=> Added support for slack_team_alias

cerberus/kubernetes/client.py, start_cerberus.py
This commits enables the status of the containers in the pods to be checked in addition to the pod status to determine go/no-go. Containers failing in a pod in addition to the pod name are logged in the report, thereby enabling the user to debug the failed pods easily.
Fixes: #49
=> Added support to report failed containers

README.md, cerberus/kubernetes/client.py, config/config.yaml, start_cerberus.py
https://github.com/openshift-scale/cerberus/issues/43
This is a start for this issue.
I created a key that is optional in a config.yaml file. It will be set to false if it not in the yaml.
Only if the watch_operators key is set to true does it get the cluster operators and verify that the degraded status is False. If the status is not false it adds the operator to the failed list which gets returned to the start_cerberus.py file to log. 
I added the key to the README.md as well. 
I definitely could get rid of monitor_cluster_operators function, it is pretty much just passing the parameters around in an extra function.
Need to fix the output the I print out to be consistent with other outputs. With a colon and take out the extra space. (Another commit to come)
Definitely might consider …
=> Adding watch of Cluster operators

cerberus/kubernetes/client.py, start_cerberus.py
This commit enables the pod crash/restart to be tracked during the wait time between each iteration. This prevents the Cerberus from missing pod crash/restarts when the pod enters the running phase before the next iteration.
Fixes: #51
=> Added support to track pod crash/restart during sleep

README.md, cerberus/kubernetes/client.py, cerberus/slack/slack_client.py, start_cerberus.py
This commit:
- Enables the nodes with specific label_selector to be listed.
- Prevents Cerberus from erroring out when key-values are not
set in the config
- Reports failed cluster operators in a slack channel
=> Fixed list_nodes, default config values, slack reporting

README.md, cerberus/kubernetes/client.py, start_cerberus.py
https://github.com/openshift-scale/cerberus/issues/42
Here I am getting the list of nodes every iteration and then finding only the master nodes and verifying that they have a NoSchedule taint status. Do I need to get the list of master nodes every iteration in case a new one gets created or one gets deleted? Or will the name/list of master nodes be consistent? 
Right now I did not add this check to the cerberus status. Do we want to add this? Or just log the scheduling status of the master nodes
=> Verify not scheduled status on master nodes

README.md, cerberus/kubernetes/client.py, start_cerberus.py
https://github.com/openshift-scale/cerberus/issues/47
This issue will monitor the downtime of the api server. If the <api-server-url>/healthz does not receive a 200 status code, it will start a timer to see the amount of downtime until the url gets a 200 status code again. 
I was only able to see this fail if I set the config to 2 seconds sleep in between each iteration.  
Will work on fixing the conflicts and will need to squash commits.
=> Monitor apiserver availability 

README.md, start_cerberus.py
This commit adds support to time the operations like watching nodes,
cluster operators, namespaces e.t.c and prints out the info after
each iteration. This will help in understanding how long each operation
is taking and act accordingly.
It will be helpful in looking at how long cerberus takes to run the
checks as wells as the impact on the timing when running it on a small
scale vs large scale clusters. Eventually they can be exposed as metrics
and act accordingly if higher latency is observed with Kube/OpenShift API.
=> Time the watch operations for each iteration

README.md, config/config.yaml, start_cerberus.py
This commit:
- Adds a high level config option called distribution to be able to
run operations which are specific to OpenShift in addition to kube
as mentioned in https://github.com/openshift-scale/cerberus/issues/42
like inspect_component mode which enables the user to
collect logs/events related to the failed component using oc inspect
command.
- Updates readme with info about setting the namespaces to monitor
in the config depending on the distribution as defaults assumes
OpenShift. It also adds pointers to the blogs and other useful resources 
related to Cerberus.
=> Separate operations based on distribution

cerberus/kubernetes/client.py
There are a couple of times I have found that when getting the cluster operators there is not a status or conditions section of the yaml. I am adding in an if/else statement for this instance and add the cluster operator to the list of failed operators if it does not have this section.
Without this code the cerberus run fails out
=> Adding check for status and condition of cluster operators

cerberus/kubernetes/client.py, cerberus/server/server.py, start_cerberus.py
This commit:
- Checks for NoSchedule taint on each master node and warns the
user if there are master nodes without NoSchedule taint.
- Performs the check once in every 10 iterations to reduce the
number of api calls.
- Uses more pythonic way to check for an empty list.
Fixes: #69
=> Added support to check for master NoSchedule taint

README.md, cerberus/kubernetes/client.py, config/config.yaml, start_cerberus.py
https://github.com/openshift-scale/cerberus/issues/48
This pull request will allow us to monitor routes associated with the defined namespaces and other routes/urls that the user specifies.
Right now I have it set up that a user will need to log in so that the api calls can use a bearer token, using the body response of "oc whoami -t". I could instead add the bearer token as a variable in the config file, what are some thoughts on this? 
Are there any times that the bearer token might not be the correct authorization when doing a GET call on the routes?
=> Monitor routes

README.md, cerberus/prometheus/client.py, config/config.yaml, start_cerberus.py
This commit will enable Cerberus to query prometheus if deployed
for KubeAPILatencyHigh alert at the end of each iteration and warns
the user if 99th percentile latency for given requests to the
kube-apiserver is above 1 second. It's the official SLI/SLO defined for
Kubernetes. Higher latency is an indicator of problem in the cluster.
Fixes https://github.com/openshift-scale/cerberus/issues/65.
=> Alert on high Kube API server latencies

README.md, config/kubernetes_config.yaml, start_cerberus.py
The system related objects in Kubernetes are placed under
kube-system namespace; therefore by default only kube-system
is placed under watch_namespaces in config file for kubernetes.
=> Added cerbeurs config file for Kubernetes distribution

cerberus/kubernetes/client.py
This commit fixes the bug encountered while retrieving all master node status when the number of master nodes is 1.
=> Fixes bug while retrieving node status

README.md, cerberus/kubernetes/client.py, config/config.yaml, start_cerberus.py
This commit enables Cerberus to handle bulk requests in chunks
instead of a single go as it can generate a very large response
when there are thousands of objects running in the cluster and
overload the server by consuming a large amount of resources.
The chunk size is set to 250 by default to break the large request
while still preserving the consistency of the total request and
improve responsiveness.
=> Reduce the load on API server for bulk requests

README.md, cerberus/kubernetes/client.py, config/config.yaml, start_cerberus.py
This commit:
- Throws an exception displaying invalid namespaces and terminates
cerberus monitoring.
- Reorders functions in cerberus/kubernetes/client.py to place similar
functions together.
- Replaces "openshift-kube-controller" with "openshift-kube-controller-manager"
as "openshift-kube-controller" isn't a valid namespace in OpenShift
by default.
Fixes: #44
=> Throw an exception when invalid namespaces are provided

README.md, containers/README.md, containers/cerberus.yml
This commit adds support to run containerized Cerberus as a Kubernetes/OpenShift deployment and thereby enabling the user to run Cerberus internally to the cluster.
=> Added support to run Cerberus as a Kubernetes Deployment

start_cerberus.py, test.sh
This commit enables the comparison of time taken for individual
checks/operations in PR against gold values in CI and displays the
percentage change.
Fixes: #81
=> Enabled operations time comparison in CI

README.md, cerberus/kubernetes/client.py, start_cerberus.py
This commit supports regex patterns to be used in watch_namespaces.
For example, `^openshift-.*$` can be used to watch all namespaces
that start with `openshift-` or `.*openshift.*` can be used to watch
all namespaces that have `openshift` in it. Providing `openshift` would
match only openshift namespace.
Fixes: #86
=> watch_namespaces supports regex patterns

README.md, config/config.yaml, start_cerberus.py
This commits supports parameterization of the http server port to enable the server run on different ports.
Fixes: #2
=> Supports http server port parameterization

README.md, cerberus/database/client.py, cerberus/kubernetes/client.py, cerberus/server/server.py, config/config.yaml, history/analysis.html, start_cerberus.py
This commit:
- Uses SQLite database to store all the failures as it is a very
light weight and portable database.
- Enables the user retrieve all the failures in a time range by
visiting the `http://0.0.0.0:8080/history?loopback=<interval>` url.
When `http://0.0.0.0:8080/history` is visited, failures in past 1 hour
are retrieved.
- Enables the user retrieve the failures between two time timestamps,
failures of specific types and failures related to specific components
by visiting `http://0.0.0.0:8080/analyze` url. The user has to apply
all the filters to scrape the failures accordingly.
Fixes: #58
=> Added support to capture failures using API

cerberus/slack/slack_client.py
for better readability in slack
```
Kubernetes master is running at https://api.msheth.perfscale.gcp.devcluster.openshift.com:6443
In iteration 3 at 2020-07-09T20:44:29, Cerberus found issues in:    
namespaces: openshift-ingress     
Hence, setting the go/no-go signal to false.     
The full report is at /tmp/cerberus on the host cerberus is running.   
```
=> add timestamp to slack messages

README.md, cerberus/inspect/inspect.py, cerberus/kubernetes/client.py, config/config.yaml, start_cerberus.py
This commit:
- Enables Cerberus to perform all checks enabled in the config
parallelly using multiprocessing.
- Uses multiprocessing to monitor namespaces in watch_namespaces
to check for failed components.
- Uses multiprocessing to collect detailed logs of failed namespaces.
- Uses multiprocessing to check for pod crash/restart in each
namespaces during the sleep interval.
The detailed description of how multiprocessing helps in speeding the Cerberus monitoring and the results for the same can be found in this [doc](https://docs.google.com/document/d/112IgkFmViu4eusUL5-6BlKbpwHGmb1YErretKn0QQ1M/edit?usp=sharing).
Fixes #23 as well
=> Enabled multiprocessing in Cerberus monitoring

README.md, config/config.yaml, custom_checks/custom_check_sample.py, start_cerberus.py
This commit enables the user to bring in additional checks to
monitor the components that are not being monitored by Cerberus.
This can be accomplished by placing the relative paths of the files
containing checks under the custom_checks option of the config.
=> Added support to allow the user to bring in additional checks

start_cerberus.py, tox.ini
This commit :
- Enables cerberus to alerts the user when an increase in etcd leader
changes are observed on the cluster. Frequent elections may be a sign
of insufficient resources, high network latency, or disruptions by
other components and should be investigated. This is just a warning
and is not taken into consideration for determining the go/no-go signal.
- Updates the linter to allow 110 chars per line.
=> Alert on high number of leader changes

cerberus/slack/slack_client.py
This commit modifies the slack integration to report failures for
each monitored cluster using threads - 1 slack thread for each
monitored cluster to help with readability as it can get messy
when using the same slack channel for multiple clusters monitored
by Cerberus.
Fixes https://github.com/openshift-scale/cerberus/issues/100
=> Report failures using slack threads

README.md
Hi,
A link in the README.md pointing to cerberus-integration is missing the '()' that translates the name wrapped in a bracket and the URL into a link markup containing. Instead they show as separate entities.  This PR adds the parenthesis and removes the empty space to enable the HTML markup to show both entities as part of the defined link.
/Jordi
=> Fixed missing parenthesis in link in README.md

containers/Dockerfile
The container needs gcc and python3-devel as the dependencies for
the image build process to succeed.
=> Bake in additional dependencies

README.md, cerberus/slack/slack_client.py, start_cerberus.py
Custom check failures are not reported on the slack channel as this functionality hasn't been added yet (Currently Cerberus supports reporting of pods, nodes and cluster operator failures only).
This PR includes the `check_returns` value to the condition that verifies criteria for reporting failure to slack channel.
=> Adding custom-check failures to slack notification

start_cerberus.py
We've recently hit this issue:
```
2021-03-12 16:32:40,706 [INFO] Exception: local variable 'custom_checks_status' referenced before assignment
```
The variable custom_checks_status needs to be initialized before so that we don't hang when custom_checks is disabled.
=> Initialize custom_checks_status

cerberus/invoke/command.py
Came across `UnboundLocalError: local variable 'output' referenced before assignment` in the recent CI run - https://ec2-52-39-240-23.us-west-2.compute.amazonaws.com:8443/job/cerberus-CI/24/console
=> fixed unbound variable error

start_cerberus.py
This code is to get around a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1958861) but would also be a useful check to verify the certain conditions of a csr's status exists as expected. 
https://github.com/cloud-bulldozer/cerberus/issues/138
=> Adding csr conditions 

setup.cfg
Correct the license declared in setup.cfg. Was set to MIT when it should be set to Apache 2.0
=> Correct license from MIT to Apache 2.0

cerberus/invoke/command.py, cerberus/kubernetes/client.py, config/config.yaml, config/kubernetes_config.yaml, start_cerberus.py
This change allows the invoke function to timeout and return a blank response when the cluster gets shut down or starts having issues 
From what I have seen I don't need to reinitialize the kubeconfig, let me know if this doesn't work for you. 
https://github.com/cloud-bulldozer/cerberus/issues/143
=> Shut down bug

containers/Dockerfile
This is needed to avoid getting rate limited.
=> Pull images from quay registry instead of docker.io

.github/workflows/docker-image.yml
Missed similar link to krkn-hub repo in github workflow 
https://github.com/cloud-bulldozer/cerberus/runs/6163504717?check_suite_focus=true
=> Krkn hub link in workflow

containers/Dockerfile, containers/build_own_image-README.md
cerberus image build fails on a couple of dependencies needed for pillow python libraries.
Also fixing instruction docs to refer to the correct repo.
=> Docs and image build fixes

cerberus/inspect/inspect.py, start_cerberus.py
When any of the cluster operators are degraded and the inspect flag is set to True, adding in a kubectl describe of the operator to be able to open bugs 
https://github.com/cloud-bulldozer/cerberus/issues/146
=> Adding co describe for any failed degraded operators 

cerberus/prometheus/client.py
The prometheus token is no longer set by default so we now have to create our own (this is for oc4.11)
Adding an OR statement to not break previous versions 
% oc -n openshift-monitoring sa get-token prometheus-k8s 
Command "get-token" is deprecated, and will be removed in the future version. Use oc create token instead.
error: could not find a service account token for service account "prometheus-k8s"
=> adding new way to get token

cerberus/kubernetes/client.py, config/config.yaml, docs/config.md, start_cerberus.py
Adding watch of terminating namespaces.  This will asses if any of the namespaces in the list of watch_namespaces are terminating and alert/set the no-go signal 
https://github.com/cloud-bulldozer/cerberus/issues/155
=> Terminating namespace

cerberus/kubernetes/client.py, config/config.yaml, config/kubernetes_config.yaml, docs/config.md, start_cerberus.py
This commit adds a way for user to specify a regex to ignore checking
the pods in the namespaces.
Fixes https://github.com/redhat-chaos/cerberus/issues/177.
=> Add support to ignore checking pods in ns

cerberus/kubernetes/client.py, start_cerberus.py
In updated python versions (>= 3.8) the default multiprocessing functionality has changed making cerberus unable to get global variables in threads on macOS. Setting a default now to be able to run on all systems
Articles I found about this
1. https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
`Changed in version 3.8: On macOS, the spawn start method is now the default. The fork start method should be considered unsafe as it can lead to crashes of the subprocess. See [bpo-33725](https://bugs.python.org/issue?@action=redirect&bpo=33725).`
2. https://stackoverflow.com/questions/70552775/multiprocess-inherently-shared-memory-in-no-longer-working-on-python-3-10-comin
=> Small needed changes to run on mac

cerberus/prometheus/client.py
Need to add the new way to get the prometheus token to not have error 
```
Command "get-token" is deprecated, and will be removed in the future version. Use oc create token instead.
error: could not find a service account token for service account "prometheus-k8s"
```
=> Adding create token

start_cerberus.py
Currently if an operator is failing it is being inspected every time no matter if inspect component is on or off. We only want to inspect if it is on/set to true
=> Only inspect operator if inspect is set

containers/Dockerfile
Want to be able to use the same base image for krkn-hub and cerberus, updating the centos image version to stream 9 
https://github.com/openshift/release/blob/9bd70917564ae6bdd0a02732a8052986d808bcb5/ci-operator/config/redhat-chaos/krkn-hub/redhat-chaos-krkn-hub-main.yaml#L5
=> Prow cerberus centos version

README.md, start_cerberus.py
need to be able to set where the output file is written to based on certain permissions
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/39697/rehearse-39697-periodic-ci-redhat-chaos-krkn-hub-main-krkn-hub-tests/1671888375042281472/artifacts/krkn-hub-tests/redhat-chaos-cerberus/build-log.txt
```
+ python3 /root/cerberus/start_cerberus.py --config=/tmp/tmp.YzZXKPpakF/cerberus_config.yaml
Traceback (most recent call last):
File "/root/cerberus/start_cerberus.py", line 557, in <module>
handlers=[logging.FileHandler("cerberus.report", mode="w"), logging.StreamHandler()],
File "/usr/lib64/python3.9/logging/__init__.py", line 1146, in __init__
StreamHandler.__init__(self, self._open())
File "/usr/lib64/python3.9/logging/__init__.py", line …
```
=> adding output file location option

start_cerberus.py
Current signal ignores any signals being sent to start_cerberus and doesnt properly end the run  
```
If you want to ignore the signal specified by the first argument (i.e., pretending that the signal never happens), use SIG_IGN for the second argument.
signal(SIGINT, SIG_IGN)
signal(SIGALRM, SIG_IGN)
In the above two lines, SIGINT and SIGALRM are ignored.
``` 
switching to using: https://python.readthedocs.io/en/latest/library/signal.html#signal.SIG_DFL
=> Kill process default usage 

config/config.yaml
OpenShift since 4.13 has defaulted to ovn-kubernetes
=> Update default cni config
